timeout: 3600s

options:
  env:
  - PROJECT_ID=$PROJECT_ID

# Deploy public Grafana instance in AppEngine
steps:
- name: gcr.io/$PROJECT_ID/gcloud-jsonnet-cbif:1.18
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -e 's|{{SERVER_ROOT_URL}}|${_SERVER_ROOT_URL}|' \
        -e 's|{{PROJECT_ID}}|${PROJECT_ID}|' \
        grafana-public/app.yaml.template > \
        grafana-public/app.yaml
- name: gcr.io/$PROJECT_ID/gcloud-jsonnet-cbif:1.18
  env:
  - PROJECT_IN=mlab-sandbox,mlab-staging
  args:
  - gcloud app deploy grafana-public/app.yaml --project $PROJECT_ID
