timeout: 3600s

options:
  env:
  - PROJECT_ID=$PROJECT_ID

# We have $_CONTAINER_IMAGE in a Cloud Build user-defined substitution variable
# because this build gets run in more projects that just the standard
# sandbox->staging->prod, but those projects are the only ones where the
# container image is built and pushed to Artifact Registry. The other
# production project where this build will happen is "measurement-lab", which
# is a production project, so we want to use the "mlab-oti" (prod) image. The
# value of this variable is defined in the build trigger of each project.
#
# Deploy public Grafana instance in AppEngine
steps:
- name: ${_CONTAINER_IMAGE}:1.1
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -e 's|{{SERVER_ROOT_URL}}|${_SERVER_ROOT_URL}|' \
        -e 's|{{PROJECT_ID}}|${PROJECT_ID}|' \
        grafana-public/app.yaml.template > \
        grafana-public/app.yaml
- name: ${_CONTAINER_IMAGE}:1.1
  env:
  - PROJECT_IN=mlab-sandbox,mlab-staging,measurement-lab
  args:
  - gcloud app deploy grafana-public/app.yaml --project $PROJECT_ID
