timeout: 3600s

options:
  env:
  - PROJECT_ID=$PROJECT_ID

# We have $_IMAGE_PROJECT in a Cloud Build user-defined substitution variable
# because this build gets run in more projects that just the standard
# sandbox->staging->prod, but those projects are the only ones where the
# container images are built and pushed to Artifact Registry. The other
# production project where this build will happen is "measurement-lab", which
# is a production project, so we want to use the "mlab-oti" (prod) image. The
# value of this variable is defined in the build trigger of each project.

# Evaluate the app.yaml.template file
steps:
- name: us-central1-docker.pkg.dev/${_IMAGE_PROJECT}/build-images/gcloud-jsonnet-cbif:1.1
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -e 's|{{SERVER_ROOT_URL}}|${_SERVER_ROOT_URL}|' \
        -e 's|{{PROJECT_ID}}|${PROJECT_ID}|' \
        grafana-public/app.yaml.template > \
        grafana-public/app.yaml

# Deploy public Grafana instance in AppEngine in sandbox and staging
- name: us-central1-docker.pkg.dev/${_IMAGE_PROJECT}/build-images/gcloud-jsonnet-cbif:1.1
  env:
  - PROJECT_IN=mlab-sandbox,mlab-staging
  args:
  - gcloud app deploy grafana-public/app.yaml --project $PROJECT_ID

# Deploy public Grafana instance in AppEngine in production
- name: us-central1-docker.pkg.dev/${_IMAGE_PROJECT}/build-images/gcloud-jsonnet-cbif:1.1
  env:
  - PROJECT_IN=measurement-lab
  args:
  - gcloud app deploy grafana-public/app.yaml grafana-public/dispatch.yaml --project $PROJECT_ID

