{
 "title": "Global Metro Dashboard (using cached data)",
 "description": "**NB: This is a pre-release subject to change, including deletion, without notification.  It is not running on production infrastructure and may be unstable.**\n\nFor all metros with 2 or more MLab sites, evaluate the quality of the interconnections between ISPs, by measuring differences in performance to MLab servers from each of the N largest Client ISPs.    If the score is poor it means that users attached to a some ISP get different performances to the different MLab servers, indicating poor connectivity between the ISPs.\nThe metrics are: KSdistance (0 is ideal), the worst case vertical distance between the cdf distributions; and spread (1 is ideal), the worst case ratio of the geometric means.\n\nWhen the spread is reported as 0, there is only one MLab site, and this analysis does not apply.\nFor more information see the [https://docs.google.com/presentation/d/1wpx45K30QD2ZIDuS5WsuRGrbcCrxs56cvuhydWRIRiw/edit?usp=sharing][slides].",
 "time": { "from": "2024-12-18T15:31:56.211Z", "to": "2024-12-18T15:41:56.211Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-bigquery-datasource" },
   {
    "name": "dataset",
    "query": "mlab-collaboration.mm_preproduction"
   },
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "ChartMetros",
    "label": "MLab Metros",
    "query": {}
   },
   { "name": "ISPcount", "label": "Client ISPs", "query": "2,3,4,5,10,20,50" },
   { "name": "verbose", "query": "no, yes" },
   { "name": "detailURL", "query": "/d/20250114a?orgId=1" },
   {
    "name": "dates",
    "label": "Date Range",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Minimum RTT pain indications",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "SELECT\n  name,\n  KSdistance*10 AS scaledKSdistance,\n  IF (Sites != '1', spread, 0) AS Spread,\n  Continent,\n  metro,\nFROM `${dataset}.cached_metro_report`(\"MinRTT\", \"${ChartMetros:regex}\", ${ISPcount})\n  JOIN (\n    SELECT\n      REGEXP_EXTRACT(site, '^([a-z]{3})') AS metro,\n      ANY_VALUE(FORMAT('%t %t (%t)', City, CountryCode,  REGEXP_EXTRACT(site, '^([a-z]{3})'))) AS name,\n      ANY_VALUE(ContinentCode) AS Continent,\n      ANY_VALUE(FORMAT('%t %t %t', ContinentCode, CountryCode , City )) AS sortKey, \n    FROM `${dataset}.cached_metadata`\n    GROUP BY metro\n  ) USING (metro)\nWHERE level like 'Metro%%'\n  AND (\"${verbose}\" = 'yes' OR Sites != '1')\nORDER BY sortKey\n"
    }
   ]
  },
  {
   "title": "Throughput pain indications",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "SELECT\n  name,\n  KSdistance*10 AS scaledKSdistance,\n  IF (Sites != '1', spread, 0) AS Spread,\n  Continent,\n  metro,\nFROM `${dataset}.cached_metro_report`(\"MeanThroughputMbps\", \"${ChartMetros:regex}\", ${ISPcount})\n  JOIN (\n    SELECT\n      REGEXP_EXTRACT(site, '^([a-z]{3})') AS metro,\n      ANY_VALUE(FORMAT('%t %t (%t)', City, CountryCode,  REGEXP_EXTRACT(site, '^([a-z]{3})'))) AS name,\n      ANY_VALUE(ContinentCode) AS Continent,\n      ANY_VALUE(FORMAT('%t %t %t', ContinentCode, CountryCode , City )) AS sortKey, \n    FROM `${dataset}.cached_metadata`\n    GROUP BY metro\n  ) USING (metro)\nWHERE level like 'Metro%%'\n  AND (\"${verbose}\" = 'yes' OR Sites != '1')\nORDER BY sortKey\n"
    }
   ]
  },
  {
   "title": "Loss Rate pain indications (Caution: noisy and not  robust)",
   "type": "barchart",
   "description": "Loss rate often varies wildly for irrelevant reasons.",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "SELECT\n  name,\n  KSdistance*10 AS scaledKSdistance,\n  IF (Sites != '1', spread, 0) AS Spread,\n  Continent,\n  metro,\nFROM `${dataset}.cached_metro_report`(\"LossRate\", \"${ChartMetros:regex}\", ${ISPcount})\n  JOIN (\n    SELECT\n      REGEXP_EXTRACT(site, '^([a-z]{3})') AS metro,\n      ANY_VALUE(FORMAT('%t %t (%t)', City, CountryCode,  REGEXP_EXTRACT(site, '^([a-z]{3})'))) AS name,\n      ANY_VALUE(ContinentCode) AS Continent,\n      ANY_VALUE(FORMAT('%t %t %t', ContinentCode, CountryCode , City )) AS sortKey, \n    FROM `${dataset}.cached_metadata`\n    GROUP BY metro\n  ) USING (metro)\nWHERE level like 'Metro%%'\n  AND (\"${verbose}\" = 'yes' OR Sites != '1')\nORDER BY sortKey\n"
    }
   ]
  }
 ]
}