{
 "title": "Metro Details Dashboard",
 "description": "Full matrix of Client ISPs and MLab Server comparisons.\n\nNB: This is a pre-release subject to changes, including deletion, without notification.  It is not running on production infrastructure and may be unstable.",
 "time": { "from": "2024-12-18T05:44:57.788Z", "to": "2024-12-18T05:49:57.788Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-bigquery-datasource" },
   {
    "name": "dataset",
    "query": "mlab-collaboration.mm_preproduction"
   },
   {
    "name": "site",
    "label": "MLab metros",
    "query": {}
   },
   { "name": "rank", "label": "Client Rows", "query": "1,2,5,10,20,50" },
   {
    "name": "ClientISP",
    "label": "Client ISPs",
    "query": {}
   },
   { "name": "mode", "query": "pdf,peak,cdf" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "# Metro Details Dashboard \n\n### Warning: This is a pre-release of research software.\nIt is not running on production infrastructure and is subject to changes or deletion without notification.\nFor documentation see the [README](/d/ef30n862ylji8a/) or scroll down for basic information. \n\nThis dashboard is obsolete and is slated to be replaced by\nthe [Regional Details Dashboard](/d/20251103a) in a future release.\n\nShow the detailed performance statistics between the top N client ISPs and all MLab sites in the selected metro.\nThe first three rows are aggregates: metro wide, by server, or by Client ISP.\n\nThe rest of the dashboard shows the performance statics individually between each of the top N Client ISPs and all MLab servers.\n\nUnder ideal conditions each Client ISP will have identical performance to each MLab site.\n\nThis data is precomputed for the date ranges shown at the top of the ISP summary table.\n\n"
   }
  },
  {
   "title": "Metro Summary Statistics -- Aggregated by the entire metro, MLab Sites and Client ISPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Summary Statistics for the top $rank ISPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "SELECT *\nFROM (\n  SELECT metro, ISPrank, tests, percent,\n  CONCAT(REGEXP_REPLACE(ISPname, '^0 ', \"\"), \" summary\")AS ISPname,\n  FROM `${dataset}.cached_metro_report`(\"MinRTT\", \"${site:regex}\", ${rank})\n  WHERE level like \"Metro%%\"  \n    UNION ALL\n  SELECT metro, ISPrank, tests, percent, ISPname\n  FROM `${dataset}.cached_metro_report`(\"MinRTT\", \"${site:regex}\", ${rank})\n  WHERE level like \"ISP%%\" \n)  ORDER BY ISPrank"
    }
   ]
  },
  {
   "title": "Aggregate minRTT for all clients using sites in ${site:raw}",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "project": "mlab-collaboration",
     "rawSql": "WITH\ndata  AS (\n  SELECT\n    bin,\n    SUM(hist) as hist,\n    metro\n  FROM `${dataset}.access_ndt7_cached_histograms`(\"MinRTT\",  \"${site:regex}\", 900)\n  GROUP BY metro, bin\n)\n\nSELECT\n  bin,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by metro)\n    WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by metro)\n    ELSE SUM(hist) OVER (PARTITION BY metro ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by metro)\n  END AS data,\n  FORMAT(\"%t (%t tests)\",metro,  SUM(hist) OVER (partition by metro)) AS metro\nFROM data\nORDER BY bin"
    }
   ]
  },
  {
   "title": "Aggregate Download Mbps for all clients using sites in ${site:raw}",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "project": "mlab-collaboration",
     "rawSql": "WITH\ndata  AS (\n  SELECT\n    bin,\n    SUM(hist) as hist,\n    metro\n  FROM `${dataset}.access_ndt7_cached_histograms`(\"MeanThroughputMbps\",  \"${site:regex}\", 900)\n  GROUP BY metro, bin\n)\n\nSELECT\n  bin,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by metro)\n    WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by metro)\n    ELSE SUM(hist) OVER (PARTITION BY metro ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by metro)\n  END AS data,\n  FORMAT(\"%t (%t tests)\",metro,  SUM(hist) OVER (partition by metro)) AS metro\nFROM data\nORDER BY bin"
    }
   ]
  },
  {
   "title": "Download MinRTT (linear mS) per Site for all Clients",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\ndata  AS (\n  SELECT\n    linBin,\n    SUM(hist) as hist,\n    siteName\n  FROM `${dataset}.access_ndt7_cached_histograms`(\"linearMinRTT\",  \"${site:regex}\", 900)\n  GROUP BY linBin, siteName\n)\n\nSELECT\n  linBin,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n    WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n    ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY linBin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n  END AS data,\n  FORMAT(\"%t (%t tests)\",siteName,  SUM(hist) OVER (partition by siteName)) AS siteName\nFROM data\nORDER BY linBin"
    }
   ]
  },
  {
   "title": "Download MinRTT (mS) per Site for all Clients",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\ndata  AS (\n  SELECT\n    bin,\n    SUM(hist) as hist,\n    siteName\n  # Uses ${datasource} implicitly\n  FROM `${dataset}.access_ndt7_cached_histograms`(\"MinRTT\",  \"${site:regex}\", 900)\n  GROUP BY bin, siteName\n)\n\nSELECT\n  bin,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n    WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n    ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n  END AS data,\n  FORMAT(\"%t (%t tests)\",siteName,  SUM(hist) OVER (partition by siteName)) AS siteName\nFROM data\nORDER BY bin"
    }
   ]
  },
  {
   "title": "Download Mbps per Site for all Clients",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\ndata  AS (\n  SELECT\n    bin,\n    SUM(hist) as hist,\n    siteName\n  FROM `${dataset}.access_ndt7_cached_histograms`(\"MeanThroughputMbps\",  \"${site:regex}\", 900)\n  GROUP BY bin, siteName\n)\n\nSELECT\n  bin,\n  CASE \"$mode\"\n    WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n    WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n    ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n  END AS data,\n  FORMAT(\"%t (%t tests)\",siteName,  SUM(hist) OVER (partition by siteName)) AS siteName,\nFROM data\nORDER BY bin\n"
    }
   ]
  },
  {
   "title": "Download MinRTT (linear mS) per top ${rank} client ISPs and selected sites. ",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\n\nISPdata AS (\n  SELECT\n    linBin,\n    SUM(hist) AS hist,\n    ISPname,\n    ISPrank\n  FROM `${dataset}.access_ndt7_cached_histograms`('linearMinRTT', \"${site:regex}\", ${rank})\n  GROUP BY ISPname, ISPrank, linBin\n)\n\nSELECT linBin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by ISPname)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by ISPname)\n      ELSE SUM(hist) OVER (PARTITION BY ISPname ORDER BY linBin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by ISPname)\n    END AS data,\n    ISPname,\n  FROM ISPdata\n  ORDER BY ISPrank, linBin\n  "
    }
   ]
  },
  {
   "title": "Download MinRTT (mS) per top $rank client ISPs and selected Sites",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\n\nISPdata AS (\n  SELECT\n    bin,\n    SUM(hist) AS hist,\n    ISPname,\n    ISPrank,\n  FROM `${dataset}.access_ndt7_cached_histograms`(\"MinRTT\", \"${site:regex}\", ${rank})\n  GROUP BY ISPname, ISPrank, bin\n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by ISPname)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by ISPname)\n      ELSE SUM(hist) OVER (PARTITION BY ISPname ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by ISPname)\n    END AS data,\n    ISPname,\n  FROM ISPdata\n  ORDER BY ISPrank, bin"
    }
   ]
  },
  {
   "title": "Download Mbps per top $rank client ISPs and selected Sites",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\n\nISPdata AS (\n  SELECT\n    bin,\n    SUM(hist) AS hist,\n    ISPname,\n    ISPrank,\n  FROM `${dataset}.access_ndt7_cached_histograms`(\"MeanThroughputMbps\", \"${site:regex}\", ${rank})\n  GROUP BY ISPname, ISPrank, bin\n  \n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by ISPname)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by ISPname)\n      ELSE SUM(hist) OVER (PARTITION BY ISPname ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by ISPname)\n    END AS data,\n    ISPname,\n  FROM ISPdata\n  ORDER BY ISPrank, bin"
    }
   ]
  },
  {
   "title": "Performance Distributions for Client ISP  $ClientISP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "ClientISP"
  },
  {
   "title": "Download MinRTT (linear mS) per MLab Site for ${ClientISP}",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\n\nISPdata AS (\n  SELECT\n    linBin,\n    SUM(hist) AS hist,\n    siteName,\n  FROM `${dataset}.access_ndt7_cached_histograms`(\"linearMinRTT\", \"${site:regex}\", ${rank})\n  WHERE ISPname IN ( \"${ClientISP:Sqlstring}\" )\n  GROUP BY siteName, linBin\n)\n\nSELECT linBin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY linBin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY linBin"
    }
   ]
  },
  {
   "title": "Download MinRTT (mS) per MLab Site for $ClientISP",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\n\nISPdata AS (\n  SELECT\n    bin,\n    SUM(hist) AS hist,\n    siteName,\n  FROM `${dataset}.access_ndt7_cached_histograms`(\"MinRTT\", \"${site:regex}\", ${rank})\n  WHERE ISPname IN ( \"${ClientISP:Sqlstring}\" )\n  GROUP BY siteName, bin\n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY bin"
    }
   ]
  },
  {
   "title": "Download  Mbps per MLab Site for $ClientISP",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "\nWITH\n\nISPdata AS (\n  SELECT\n    bin,\n    SUM(hist) AS hist,\n    siteName,\n  FROM `${dataset}.access_ndt7_cached_histograms`(\"MeanThroughputMbps\", \"${site:regex}\", ${rank})\n  WHERE ISPname IN ( \"${ClientISP:Sqlstring}\" )\n  GROUP BY siteName, bin\n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY bin"
    }
   ]
  }
 ]
}