{
 "title": "Prototype",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "continent",
    "label": "Continent",
    "query": {}
   },
   {
    "name": "country",
    "label": "Country",
    "query": {}
   },
   {
    "name": "clientASN",
    "label": "Client ASN",
    "query": {}
   },
   { "name": "percentile", "label": "Percentile", "query": "1,50, 95, 100" },
   { "name": "time_segment", "label": "Per", "query": "hour,day" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# M-Lab Dashboard\n\ncountry: ${country}\n\ntimefilter: $__timeFilter\n\n\ncountry regex: ${country:regex}"
   }
  },
  {
   "title": "Total Tests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "measurement-lab",
     "rawSql": "WITH undefined as (\nSELECT\n  IF ((client.Geo.City = \"\" OR client.Geo.City IS NULL), \"undefined\", client.Geo.City) as city,\n  IF ((client.Geo.CountryName = \"\" OR client.Geo.CountryName IS NULL), \"undefined\", REPLACE(client.Geo.CountryName, \".\", \"\")) as country,\n  IF ((client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_downloads`\nWHERE\n  $__timeFilter(TIMESTAMP(date)) \n  AND REGEXP_CONTAINS(client.Geo.ContinentCode, \"${continent:regex}\")\n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\n  AND (filter.IsComplete AND filter.IsProduction AND NOT filter.IsError AND NOT filter.IsOAM AND NOT filter.IsPlatformAnomaly\n        AND NOT filter.IsSmall AND NOT filter.IsShort AND NOT filter.IsLong AND NOT filter._IsRFC1918)\n)\n\nSELECT\n  COUNT(*)\nFROM undefined\nWHERE --REGEXP_CONTAINS(city, \"${city:regex}\")\n  IF(\"${clientASN}\" = \"all\", TRUE, REGEXP_CONTAINS(clientASN, \"${clientASN:regex}\"))\n"
    }
   ]
  },
  {
   "title": "Download (Mbps)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "measurement-lab",
     "rawSql": "WITH undefined as (\nSELECT\n  IF ((client.Geo.City = \"\" OR client.Geo.City IS NULL), \"undefined\", client.Geo.City) as city,\n  IF ((client.Geo.CountryName = \"\" OR client.Geo.CountryName IS NULL), \"undefined\", REPLACE(client.Geo.CountryName, \".\", \"\")) as country,\n  IF ((client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN,\n  a.MeanThroughputMbps as download\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_downloads`\nWHERE\n  $__timeFilter(TIMESTAMP(date)) \n  AND REGEXP_CONTAINS(client.Geo.ContinentCode, \"${continent:regex}\")\n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\n  AND (filter.IsComplete AND filter.IsProduction AND NOT filter.IsError AND NOT filter.IsOAM AND NOT filter.IsPlatformAnomaly\n        AND NOT filter.IsSmall AND NOT filter.IsShort AND NOT filter.IsLong AND NOT filter._IsRFC1918)\n)\n\nSELECT\n  APPROX_QUANTILES(undefined.download, 100)[OFFSET(${percentile})]\nFROM undefined\nWHERE --REGEXP_CONTAINS(city, \"${city:regex}\")\n  IF(\"${clientASN}\"= \"all\", TRUE, REGEXP_CONTAINS(clientASN, \"${clientASN:regex}\"))"
    }
   ]
  },
  {
   "title": "Upload (Mbps)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "measurement-lab",
     "rawSql": "WITH undefined as (\nSELECT\n  IF ((client.Geo.City = \"\" OR client.Geo.City IS NULL), \"undefined\", client.Geo.City) as city,\n  IF ((client.Geo.CountryName = \"\" OR client.Geo.CountryName IS NULL), \"undefined\", REPLACE(client.Geo.CountryName, \".\", \"\")) as country,\n  IF ((client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN,\n  a.MeanThroughputMbps as upload\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_uploads`\nWHERE\n  $__timeFilter(TIMESTAMP(date)) \n  AND REGEXP_CONTAINS(client.Geo.ContinentCode, \"${continent:regex}\")\n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\n  AND (filter.IsComplete AND filter.IsProduction AND NOT filter.IsError AND NOT filter.IsOAM AND NOT filter.IsPlatformAnomaly\n        AND NOT filter.IsSmall AND NOT filter.IsShort AND NOT filter.IsLong AND NOT filter._IsRFC1918)\n)\n\nSELECT\n  APPROX_QUANTILES(undefined.upload, 100)[OFFSET(${percentile})]\nFROM undefined\nWHERE --REGEXP_CONTAINS(city, \"${city:regex}\")\n  IF(\"${clientASN}\"= \"all\", TRUE, REGEXP_CONTAINS(clientASN, \"${clientASN:regex}\"))"
    }
   ]
  },
  {
   "title": "NDT download count",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "location": "US",
     "project": "measurement-lab",
     "rawSql": "WITH undefined as (\nSELECT\n  IF ((client.Geo.City = \"\" OR client.Geo.City IS NULL), \"undefined\", client.Geo.City) as city,\n  IF ((client.Geo.CountryName = \"\" OR client.Geo.CountryName IS NULL), \"undefined\", REPLACE(client.Geo.CountryName, \".\", \"\")) as country,\n  IF ((client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN,\n  a.TestTime as time\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_downloads`\nWHERE\n  $__timeFilter(TIMESTAMP(date)) \n  AND REGEXP_CONTAINS(client.Geo.ContinentCode, \"${continent:regex}\")\n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\n  AND (filter.IsComplete AND filter.IsProduction AND NOT filter.IsError AND NOT filter.IsOAM AND NOT filter.IsPlatformAnomaly\n        AND NOT filter.IsSmall AND NOT filter.IsShort AND NOT filter.IsLong AND NOT filter._IsRFC1918)\n)\n\nSELECT\n  TIMESTAMP_TRUNC(undefined.time, ${time_segment}) as time,\n  COUNT(*) as value\nFROM undefined\nWHERE --REGEXP_CONTAINS(city, \"${city:regex}\")\n  IF(\"${clientASN}\"= \"all\", TRUE, REGEXP_CONTAINS(undefined.clientASN, \"${clientASN:regex}\"))\nGROUP by time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Download (Mbps)",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "location": "US",
     "project": "measurement-lab",
     "rawSql": "WITH undefined as (\nSELECT\n  IF ((client.Geo.City = \"\" OR client.Geo.City IS NULL), \"undefined\", client.Geo.City) as city,\n  IF ((client.Geo.CountryName = \"\" OR client.Geo.CountryName IS NULL), \"undefined\", REPLACE(client.Geo.CountryName, \".\", \"\")) as country,\n  IF ((client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN,\n  a.TestTime as time,\n  a.MeanThroughputMbps as download\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_downloads`\nWHERE\n  $__timeFilter(TIMESTAMP(date)) \n  AND REGEXP_CONTAINS(client.Geo.ContinentCode, \"${continent:regex}\")\n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\n  AND (filter.IsComplete AND filter.IsProduction AND NOT filter.IsError AND NOT filter.IsOAM AND NOT filter.IsPlatformAnomaly\n        AND NOT filter.IsSmall AND NOT filter.IsShort AND NOT filter.IsLong AND NOT filter._IsRFC1918)\n)\n\nSELECT\n  TIMESTAMP_TRUNC(undefined.time,  ${time_segment}) as time,\n  APPROX_QUANTILES(undefined.download, 100)[OFFSET(${percentile})]\nFROM undefined\nWHERE --REGEXP_CONTAINS(city, \"${city:regex}\")\n  IF(\"${clientASN}\"= \"all\", TRUE, REGEXP_CONTAINS(undefined.clientASN, \"${clientASN:regex}\"))\nGROUP by time\nORDER BY time "
    }
   ]
  },
  {
   "title": "Upload (Mbps)",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "location": "US",
     "project": "measurement-lab",
     "rawSql": "WITH undefined as (\nSELECT\n  IF ((client.Geo.City = \"\" OR client.Geo.City IS NULL), \"undefined\", client.Geo.City) as city,\n  IF ((client.Geo.CountryName = \"\" OR client.Geo.CountryName IS NULL), \"undefined\", REPLACE(client.Geo.CountryName, \".\", \"\")) as country,\n  IF ((client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN,\n  a.TestTime as time,\n  a.MeanThroughputMbps as upload\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_uploads`\nWHERE\n  $__timeFilter(TIMESTAMP(date)) \n  AND REGEXP_CONTAINS(client.Geo.ContinentCode, \"${continent:regex}\")\n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\n  AND (filter.IsComplete AND filter.IsProduction AND NOT filter.IsError AND NOT filter.IsOAM AND NOT filter.IsPlatformAnomaly\n        AND NOT filter.IsSmall AND NOT filter.IsShort AND NOT filter.IsLong AND NOT filter._IsRFC1918)\n)\n\nSELECT\n  TIMESTAMP_TRUNC(undefined.time,  ${time_segment}) as time,\n  APPROX_QUANTILES(undefined.upload, 100)[OFFSET(${percentile})]\nFROM undefined\nWHERE --REGEXP_CONTAINS(city, \"${city:regex}\")\n  IF(\"${clientASN}\"= \"all\", TRUE, REGEXP_CONTAINS(undefined.clientASN, \"${clientASN:regex}\"))\nGROUP by time\nORDER BY time "
    }
   ]
  },
  {
   "title": "Test count per Top 5 ASN ",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "location": "US",
     "project": "measurement-lab",
     "rawSql": "WITH clientASNs as (\nSELECT   \n  IF (( client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN, \n  COUNT(*) as count\nFROM `measurement-lab.ndt.ndt7`\nWHERE\n  $__timeFilter(TIMESTAMP(date))\n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\nGROUP BY clientASN\nORDER by count DESC\nLIMIT 5\n),\n\nundefined as (\nSELECT\n  IF ((client.Geo.City = \"\" OR client.Geo.City IS NULL), \"undefined\", client.Geo.City) as city,\n  IF ((client.Geo.CountryName = \"\" OR client.Geo.CountryName IS NULL), \"undefined\", REPLACE(client.Geo.CountryName, \".\", \"\")) as country,\n  IF (( client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN,\n  a.TestTime as time,\n  a.MeanThroughputMbps as download\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_downloads` \nWHERE\n  $__timeFilter(TIMESTAMP(date)) \n  AND REGEXP_CONTAINS(client.Geo.ContinentCode, \"${continent:regex}\")\n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\n  AND (filter.IsComplete AND filter.IsProduction AND NOT filter.IsError AND NOT filter.IsOAM AND NOT filter.IsPlatformAnomaly\n        AND NOT filter.IsSmall AND NOT filter.IsShort AND NOT filter.IsLong AND NOT filter._IsRFC1918)\n)\n\nSELECT\n  TIMESTAMP_TRUNC(undefined.time,  ${time_segment}) as time,\n  clientASNs.clientASN as clientASN,\n  COUNT(*) as count\nFROM clientASNs INNER JOIN undefined on clientASNs.clientASN = undefined.clientASN \nWHERE --REGEXP_CONTAINS(city, \"${city:regex}\")\n  IF(\"${clientASN}\"= \"all\", TRUE, REGEXP_CONTAINS(undefined.clientASN, \"${clientASN:regex}\"))\nGROUP by time, clientASN\nORDER BY time \n"
    }
   ]
  },
  {
   "title": "Download per Top 5 ASN (Mbps)",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "location": "US",
     "project": "measurement-lab",
     "rawSql": "WITH clientASNs as (\nSELECT   \n  IF (( client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN, \n  COUNT(*) as count\nFROM `measurement-lab.ndt.ndt7`\nWHERE \n  $__timeFilter(TIMESTAMP(date)) \n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\nGROUP BY clientASN\nORDER by count DESC\nLIMIT 5\n),\n\nundefined as (\nSELECT\n  IF ((client.Geo.City = \"\" OR client.Geo.City IS NULL), \"undefined\", client.Geo.City) as city,\n  IF ((client.Geo.CountryName = \"\" OR client.Geo.CountryName IS NULL), \"undefined\", REPLACE(client.Geo.CountryName, \".\", \"\")) as country,\n  IF (( client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN,\n  a.TestTime as time,\n  a.MeanThroughputMbps as download\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_downloads` \nWHERE\n  $__timeFilter(TIMESTAMP(date)) \n  AND REGEXP_CONTAINS(client.Geo.ContinentCode, \"${continent:regex}\")\n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\n  AND (filter.IsComplete AND filter.IsProduction AND NOT filter.IsError AND NOT filter.IsOAM AND NOT filter.IsPlatformAnomaly\n        AND NOT filter.IsSmall AND NOT filter.IsShort AND NOT filter.IsLong AND NOT filter._IsRFC1918)\n)\n\nSELECT\n  TIMESTAMP_TRUNC(undefined.time,  ${time_segment}) as time,\n  clientASNs.clientASN as clientASN,\n  APPROX_QUANTILES(undefined.download, 100)[OFFSET(${percentile})]\nFROM clientASNs INNER JOIN undefined on clientASNs.clientASN = undefined.clientASN \nWHERE --REGEXP_CONTAINS(city, \"${city:regex}\")\n  IF(\"${clientASN}\"= \"all\", TRUE, REGEXP_CONTAINS(undefined.clientASN, \"${clientASN:regex}\"))\nGROUP by time, clientASN\nORDER BY time \n"
    }
   ]
  },
  {
   "title": "Download per Top 5 ASN (Mbps)",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "location": "US",
     "project": "measurement-lab",
     "rawSql": "WITH clientASNs as (\nSELECT   \n  IF (( client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN, \n  COUNT(*) as count\nFROM `measurement-lab.ndt.ndt7`\nWHERE \n  $__timeFilter(TIMESTAMP(date)) \n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\nGROUP BY clientASN\nORDER by count DESC\nLIMIT 5\n),\n\nundefined as (\nSELECT\n  IF ((client.Geo.City = \"\" OR client.Geo.City IS NULL), \"undefined\", client.Geo.City) as city,\n  IF ((client.Geo.CountryName = \"\" OR client.Geo.CountryName IS NULL), \"undefined\", REPLACE(client.Geo.CountryName, \".\", \"\")) as country,\n  IF (( client.Network.ASName = \"\" OR client.Network.ASName IS NULL), \"undefined\", REPLACE(client.Network.ASName, \".\", \"\")) as clientASN,\n  a.TestTime as time,\n  a.MeanThroughputMbps as download\nFROM `measurement-lab.ndt_intermediate.extended_ndt7_downloads` \nWHERE\n  $__timeFilter(TIMESTAMP(date)) \n  AND REGEXP_CONTAINS(client.Geo.ContinentCode, \"${continent:regex}\")\n  AND IF(\"${country}\" = \"all\", TRUE, REGEXP_CONTAINS(client.Geo.CountryName, \"${country:regex}\"))\n  AND (filter.IsComplete AND filter.IsProduction AND NOT filter.IsError AND NOT filter.IsOAM AND NOT filter.IsPlatformAnomaly\n        AND NOT filter.IsSmall AND NOT filter.IsShort AND NOT filter.IsLong AND NOT filter._IsRFC1918)\n)\n\nSELECT\n  TIMESTAMP_TRUNC(undefined.time,  ${time_segment}) as time,\n  clientASNs.clientASN as clientASN,\n  APPROX_QUANTILES(undefined.download, 100)[OFFSET(${percentile})]\nFROM clientASNs INNER JOIN undefined on clientASNs.clientASN = undefined.clientASN \nWHERE --REGEXP_CONTAINS(city, \"${city:regex}\")\n  IF(\"${clientASN}\"= \"all\", TRUE, REGEXP_CONTAINS(undefined.clientASN, \"${clientASN:regex}\"))\nGROUP by time, clientASN\nORDER BY time \n"
    }
   ]
  }
 ]
}