{
 "title": "Public Regional Details Dashboard",
 "description": "Selectable matrix of Client ISPs and MLab Server comparisons, circa an anchor metro.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-bigquery-datasource" },
   {
    "name": "dataset",
    "query": "mlab-collaboration.mm_preproduction"
   },
   { "name": "method", "query": "cached, live, experimental" },
   {
    "name": "anchor",
    "label": "Anchor metro",
    "query": {}
   },
   { "name": "radius", "label": "Radius (kM)", "query": "1, 100, 500" },
   {
    "name": "region",
    "label": "Servers",
    "query": {}
   },
   { "name": "ISPcount", "label": "Client Rows", "query": "0,1,2,3,4,5,10,20,50" },
   {
    "name": "ClientISP",
    "label": "Client ISPs",
    "query": {}
   },
   { "name": "mode", "query": "pdf,peak,cdf" },
   { "name": "binSize", "query": "50, 25, 10, 5, 2, 1" },
   { "name": "xAxis", "query": "none, day, hour" },
   {
    "name": "table_field",
    "label": "Table Field",
    "query": "MinRTT, MeanThroughputMbps, uploadMeanThroughputMbps, LossRate, linearMinRTT, linearMSS, RTO, fineMeanThroughputMbps"
   },
   { "name": "verbose", "query": "false, true" },
   {
    "name": "field",
    "label": "Fourth column",
    "query": "none, MinRTT, MeanThroughputMbps, uploadMeanThroughputMbps, LossRate, RTO"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Regional Details Dashboard\n### Warning: This is a pre-release of experimental software.\nIt is not running on production infrastructure and is subject to changes or deletion without notification.\nFor documentation see the [README](/d/ef30n862ylji8a/) or scroll down for basic information. \n\nThe Anchor Metro is used to preselect servers (within the selected radus)\nand preselect client ISPs (by rank in the anchor metro).\n\nData is shown for all selected Severs cross all selected Client ISPs.\n\nNote that the client data is preselected by rank independently in each metro.\nIf a client ISP's rank differs between metros, some of its data might not be shown.\nTo workaround this, select extra client rows,\nbeyond the last clinetISP that you want to select.\n\nIf shown method selects the backend: Please use cached.\n\n"
   }
  },
  {
   "title": ". . . . .  Diagnostic Panel",
   "type": "table",
   "gridPos": { "h": 1, "w": 1, "x": 12, "y": 0 },
   "targets": [
    {
     "project": "mlab-collaboration",
     "rawSql": "SELECT \"{dataset}\" AS name, \"${dataset}\" AS value\nUNION ALL SELECT \"{method}\", \"${method}\"\nUNION ALL SELECT \"{anchor}\", \"${anchor}\"\nUNION ALL SELECT \"{radius}\", \"${radius}\"\nUNION ALL SELECT \"{region:regex}\", \"${region:regex}\"\nUNION ALL SELECT \"{ISPcount}\", \"${ISPcount}\"\nUNION ALL SELECT \"{ClientISP:regex}\", \"${ClientISP:regex}\"\n-- Consider dates\n"
    }
   ]
  },
  {
   "title": "Summary Statistics for the top ISPs in $anchor",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "\nSELECT level, Metric, Sites, tests, pct, KSdistance,\n  KSoutlier AS KS_breadcrumb, Spread, SPoutlier AS SP_Breadcrumb, ISPname\nFROM (\n  SELECT * EXCEPT (ISPname),\n  data AS metric,\n  percent AS pct,\n  IF (level like \"Regional Summary\",\n    FORMAT (\"%t summary\", REGEXP_REPLACE(ISPname, '^0 ', \"\")),\n    ISPname\n    ) AS ISPname,\n  -- FROM `${dataset}.cached_metro_report`(\"MinRTT\", \"${site:regex}\", ${ISPcount})\n  FROM `${dataset}.regional_report` (\"${method}\",\"${xAxis}\", ${binSize}, \"${table_field}\",\n    DATE(REGEXP_EXTRACT(\"${__from:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    DATE(REGEXP_EXTRACT(\"${__to:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    \"^(${region:regex})\", \"^(${ClientISP:regex})\", ${ISPcount})\n  WHERE ${verbose} OR level like \"Regional Summary\" OR level LIKE \"ISP%%\"  \n)"
    }
   ]
  },
  {
   "title": "Performance Distributions for Client ISP  $ClientISP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "ClientISP"
  },
  {
   "title": "Download MinRTT (linear mS) per MLab Site for ${ClientISP}",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\n\nISPdata AS (\n  SELECT\n    bin,\n    binIX,\n    CAST(ROUND(binIX / 50.0 * ${binSize}) AS INT) AS thinedIX,\n    SUM(hist) AS hist,\n    siteName,\n  FROM `${dataset}.access_ndt7_isp_histograms` (\"${method}\", \"${xAxis}\", ${binSize}, \"MinRTT\",\n    DATE(REGEXP_EXTRACT(\"${__from:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    DATE(REGEXP_EXTRACT(\"${__to:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    \"${region:regex}\", ${ISPcount})\n  WHERE  REGEXP_CONTAINS ( ISPname, \"^(${ClientISP:regex})\" )\n  GROUP BY siteName, thinedIX, binIX, bin\n  HAVING (binIX = thinedIX * 50 / ${binSize}) OR (\"$mode\" = \"cdf\")\n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY bin"
    }
   ]
  },
  {
   "title": "Download MinRTT (mS) per MLab Site for $ClientISP",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\n\nISPdata AS (\n  SELECT\n    bin,\n    binIX,\n    CAST(ROUND(binIX / 50.0 * ${binSize}) AS INT) AS thinedIX,\n    SUM(hist) AS hist,\n    siteName,\n  FROM `${dataset}.access_ndt7_isp_histograms` (\"${method}\", \"${xAxis}\", ${binSize}, \"MinRTT\",\n    DATE(REGEXP_EXTRACT(\"${__from:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    DATE(REGEXP_EXTRACT(\"${__to:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    \"${region:regex}\", ${ISPcount})\n  WHERE  REGEXP_CONTAINS ( ISPname, \"^(${ClientISP:regex})\" )\n  GROUP BY siteName, thinedIX, binIX, bin\n  HAVING (binIX = thinedIX * 50 / ${binSize}) OR (\"$mode\" = \"cdf\")\n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY bin"
    }
   ]
  },
  {
   "title": "Download  Mbps per MLab Site for $ClientISP",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "\nWITH\n\nISPdata AS (\n  SELECT\n    bin,\n    binIX,\n    CAST(ROUND(binIX / 50.0 * ${binSize}) AS INT) AS thinedIX,\n    SUM(hist) AS hist,\n    siteName,\n  FROM `${dataset}.access_ndt7_isp_histograms` (\"${method}\", \"${xAxis}\", ${binSize}, \"MeanThroughputMbps\",\n    DATE(REGEXP_EXTRACT(\"${__from:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    DATE(REGEXP_EXTRACT(\"${__to:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    \"${region:regex}\", ${ISPcount})\n  WHERE  REGEXP_CONTAINS ( ISPname, \"^(${ClientISP:regex})\" )\n  GROUP BY siteName, thinedIX, binIX, bin\n  HAVING (binIX = thinedIX * 50 / ${binSize}) OR (\"$mode\" = \"cdf\")\n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY bin"
    }
   ]
  },
  {
   "title": "Download  $field per MLab Site for $ClientISP",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "\nWITH\n\nISPdata AS (\n  SELECT\n    bin,\n    SUM(hist) AS hist,\n    siteName,\n  -- FROM `${dataset}.access_ndt7_cached_histograms`(\"MeanThroughputMbps\", \"${region:regex}\", ${ISPrank})\n  FROM `${dataset}.access_ndt7_isp_histograms` (\"${method}\", \"${xAxis}\", ${binSize}, \"${field}\",\n    DATE(REGEXP_EXTRACT(\"${__from:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    DATE(REGEXP_EXTRACT(\"${__to:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    \"${region:regex}\", ${ISPcount})\n\n  WHERE  REGEXP_CONTAINS ( ISPname, \"^(${ClientISP:regex})\" )\n  GROUP BY siteName, bin\n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY bin"
    }
   ]
  }
 ]
}