{
 "title": "MLab Regional Details Dashboard",
 "description": "Full matrix of Client ISPs and MLab Server comparisons, circa an anchor metro.",
 "time": { "from": "2025-06-04T00:00:00.000Z", "to": "2025-06-10T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-bigquery-datasource" },
   {
    "name": "dataset",
    "query": "mlab-collaboration.mm_preproduction"
   },
   { "name": "method", "query": "cached, live, experimental" },
   {
    "name": "field",
    "query": "MinRTT, MeanThroughputMbps, uploadMeanThroughputMbps, LossRate, linearMinRTT, linearMSS, RTO, fineMeanThroughputMbps"
   },
   {
    "name": "anchor",
    "label": "Anchor metro",
    "query": {}
   },
   { "name": "radius", "label": "Radius (kM)", "query": "500" },
   {
    "name": "region",
    "label": "Servers",
    "query": {}
   },
   { "name": "selectorISPcount", "label": "Client Rows", "query": "0,1,2,3,4,5,10,20,50" },
   {
    "name": "ClientISP",
    "label": "Client ISPs",
    "query": {}
   },
   { "name": "mode", "query": "pdf,peak,cdf" },
   { "name": "xAxis", "query": "none, day, hour" },
   {
    "name": "ISPcount",
    "query": "(${selectorISPcount}*2), (${selectorISPcount}*4)"
   },
   { "name": "binSize", "query": "50" },
   { "name": "verbose", "query": "false, true" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Regional Details Dashboard \n\n### MLab Internal version\nCAUTION this version changes frequently\n\nScroll for more info.\n\nThe servers (the region) are selected by distance from the Anchor metro.\n\nThe Client ISPs are selected by rank in the Anchor metro.\n\nData is shown for all selected severs cross all selected Client ISPs.\n\nMethod selects the backend; Please select cached.\n\nFor more information see the\n[slides](https://docs.google.com/presentation/d/1wpx45K30QD2ZIDuS5WsuRGrbcCrxs56cvuhydWRIRiw/edit?usp=sharing)."
   }
  },
  {
   "title": "Diagnostic Panel",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "project": "mlab-collaboration",
     "rawSql": "SELECT \"region:regexp\" AS Name, \"${region:regexp}\" AS Value\n  UNION ALL\nSELECT \"ClientISP\", \"${ClientISP}\"\n  UNION ALL\nSELECT \"anchor\", \"$anchor\"\n  UNION ALL\nSELECT \"anchor:regex\", \"${anchor:regex}\""
    }
   ]
  },
  {
   "title": "Metro Summary Statistics -- Aggregated by the entire metro, MLab Sites and Client ISPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Summary Statistics for the top ISPs in $anchor",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "project": "mlab-oti",
     "rawSql": "\nSELECT level, Metric, Sites, tests, pct, KSdistance, KSoutlier, Spread, SPoutlier, ISPname\nFROM (\n  SELECT * EXCEPT (ISPname),\n  data AS metric,\n  percent AS pct,\n  IF (level like \"Regional Summary\",\n    FORMAT (\"%t summary\", REGEXP_REPLACE(ISPname, '^0 ', \"\")),\n    ISPname\n    ) AS ISPname,\n  -- FROM `${dataset}.cached_metro_report`(\"MinRTT\", \"${site:regex}\", ${ISPcount})\n  FROM `${dataset}.regional_report` (\"${method}\",\"${xAxis}\", ${binSize}, \"${field}\",\n    DATE(REGEXP_EXTRACT(\"${__from:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    DATE(REGEXP_EXTRACT(\"${__to:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    \"^(${region:regex})\", \"^(${ClientISP:regex})\", ${ISPcount})\n  WHERE ${verbose} OR level like \"Regional Summary\" OR level LIKE \"ISP%%\"  \n)"
    }
   ]
  },
  {
   "title": "Performance Distributions for Client ISP  $ClientISP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "ClientISP"
  },
  {
   "title": "Download MinRTT (linear mS) per MLab Site for ${ClientISP}",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\n\nISPdata AS (\n  SELECT\n    linBin,\n    SUM(hist) AS hist,\n    siteName,\n  -- FROM `${dataset}.access_ndt7_cached_histograms`(\"linearMinRTT\", \"${region:regex}\", ${rank})\n  FROM `${dataset}.access_ndt7_isp_histograms` (\"${method}\", \"${xAxis}\", ${binSize}, \"linearMinRTT\",\n    DATE(REGEXP_EXTRACT(\"${__from:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    DATE(REGEXP_EXTRACT(\"${__to:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    \"${region:regex}\", ${ISPcount})\n\n  WHERE  REGEXP_CONTAINS ( ISPname, \"^(${ClientISP:regex})\" )\n  GROUP BY siteName, linBin\n)\n\nSELECT linBin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY linBin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY linBin"
    }
   ]
  },
  {
   "title": "Download MinRTT (mS) per MLab Site for $ClientISP",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "WITH\n\nISPdata AS (\n  SELECT\n    bin,\n    SUM(hist) AS hist,\n    siteName,\n  -- FROM `${dataset}.access_ndt7_cached_histograms`(\"MinRTT\", \"${region:regex}\", ${rank})\n  FROM `${dataset}.access_ndt7_isp_histograms` (\"${method}\", \"${xAxis}\", ${binSize}, \"MinRTT\",\n    DATE(REGEXP_EXTRACT(\"${__from:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    DATE(REGEXP_EXTRACT(\"${__to:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n\"${region:regex}\", ${ISPcount})\n\n  WHERE  REGEXP_CONTAINS ( ISPname, \"^(${ClientISP:regex})\" )\n  GROUP BY siteName, bin\n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY bin"
    }
   ]
  },
  {
   "title": "Download  Mbps per MLab Site for $ClientISP",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "\nWITH\n\nISPdata AS (\n  SELECT\n    bin,\n    SUM(hist) AS hist,\n    siteName,\n  -- FROM `${dataset}.access_ndt7_cached_histograms`(\"MeanThroughputMbps\", \"${region:regex}\", ${rank})\n  FROM `${dataset}.access_ndt7_isp_histograms` (\"${method}\", \"${xAxis}\", ${binSize}, \"MeanThroughputMbps\",\n    DATE(REGEXP_EXTRACT(\"${__from:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    DATE(REGEXP_EXTRACT(\"${__to:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    \"${region:regex}\", ${ISPcount})\n\n  WHERE  REGEXP_CONTAINS ( ISPname, \"^(${ClientISP:regex})\" )\n  GROUP BY siteName, bin\n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY bin"
    }
   ]
  },
  {
   "title": "Download  $field per MLab Site for $ClientISP",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "mlab-oti",
     "rawSql": "\nWITH\n\nISPdata AS (\n  SELECT\n    bin,\n    SUM(hist) AS hist,\n    siteName,\n  -- FROM `${dataset}.access_ndt7_cached_histograms`(\"MeanThroughputMbps\", \"${region:regex}\", ${ISPrank})\n  FROM `${dataset}.access_ndt7_isp_histograms` (\"${method}\", \"${xAxis}\", ${binSize}, \"${field}\",\n    DATE(REGEXP_EXTRACT(\"${__from:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    DATE(REGEXP_EXTRACT(\"${__to:date:iso}\", '[0-9]{4}-[0-9]{2}-[0-9]{2}')),\n    \"${region:regex}\", ${ISPcount})\n\n  WHERE  REGEXP_CONTAINS ( ISPname, \"^(${ClientISP:regex})\" )\n  GROUP BY siteName, bin\n)\n\nSELECT bin,\n    CASE \"$mode\"\n      WHEN \"pdf\" THEN hist / SUM(hist) OVER (partition by siteName)\n      WHEN \"peak\" THEN hist / MAX(hist) OVER (partition by siteName)\n      ELSE SUM(hist) OVER (PARTITION BY siteName ORDER BY bin ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) / SUM(hist) OVER (partition by siteName)\n    END AS data,\n    siteName,\n  FROM ISPdata\n  ORDER BY bin"
    }
   ]
  }
 ]
}